name: Speech-Synthesis
version: 0.01
abstract: A generic interface for different Text To Speech Engines
author: Jouke Visser <jouke@pvoice.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
